### ISSUE TITLE
Add thew "new_conversation" parameter to virtual device calls

### ISSUE THREAD

**Issue by dmarvp** [bespoken/virtual-device-sdk#101]
**Is your feature request related to a problem? Please describe.**
When using tests for Google virtual devices, the session does not end in between calls, so consecutive tests of the same interaction will fail if the google action is not exited explicitly.

**Describe the solution you'd like**
The virtual device endpoints have a parameter called new_conversation (must be set to true) that will force start a new conversation with the Google Assistant SDK. We should expose that parameter as we do for message, locale, voiceId and phrases for sequential validation. That way, we can set it to true on the first interaction with the virtual device, and false on the following.

As for batch validation, we should always set it to true.

**Additional context**
Please inform @AnkRaiza when a new release is done so that we can include this in dashboard.

**Comment by ecruzado** [comment]
https://github.com/bespoken/virtual-device-sdk/pull/104
