### ISSUE TITLE
Messages and phrases are not being correctly encoded in sequential validation

### ISSUE THREAD

**Issue by dmarvp** [bespoken/virtual-device-sdk#102]
### Description:
When using messages and phrases like "what is rock & roll?", they are being sent to the virtual device as it is. This means, that they are interpreted as parameters and so we only receive "what is rock".

### Environment:
- Version: 1.5.3

### Steps To Reproduce
1. Use the message function to send the message "what is rock & roll"

### Expected behavior
The message and phrases should be correctly encoded.

### Actual behavior
The message and phrases are not correctly encoded and are sent as they are.

### Additional context
This ticket was born from https://github.com/bespoken/dashboard/issues/1014
The solution should be to encode message and phrases here: 
https://github.com/bespoken/virtual-device-sdk/blob/e0a70a93f69cacff2583499561bd77c41cdfd0d8/src/VirtualDevice.ts#L41
and here
https://github.com/bespoken/virtual-device-sdk/blob/e0a70a93f69cacff2583499561bd77c41cdfd0d8/src/VirtualDevice.ts#L46

Please write tests to confirm it works.

**Comment by ecruzado** [comment]
https://github.com/bespoken/virtual-device/pull/233

**Comment by ecruzado** [comment]
https://github.com/bespoken/virtual-device-sdk/pull/103
