### ISSUE TITLE
Show trial expire error message

### ISSUE THREAD

**Issue by AnkRaiza** [bespoken/virtual-device-sdk#108]
### Steps To Reproduce
1. Run a test with expired token
2. wait for it to finish
3. see that there is a general undefined error

### Expected behavior
The error should say that the trial token is expired

### Actual behavior
The error is a general undefined error

**Comment by ecruzado** [comment]
can be tested on https://github.com/bespoken/virtual-device-sdk/releases/tag/v1.5.17

**Comment by MKen-li** [comment]
Marked as verified
