### ISSUE TITLE
Add a sttClient parameter

### ISSUE THREAD

**Issue by dmarvp** [bespoken/virtual-device-sdk#114]
### Description
From: https://github.com/bespoken/virtual-device/issues/260

The stt flag should also be exposed via the virtual device SDK. It should be able to be set similar to the other optional flags on the virtual device:
https://github.com/bespoken/virtual-device-sdk/blob/master/src/VirtualDevice.ts#L12

**Comment by ecruzado** [comment]
https://github.com/bespoken/virtual-device-sdk/pull/116

**Comment by MKen-li** [comment]
No QA needed
