### ISSUE TITLE
Add deviceLocation as a property in the sdk

### ISSUE THREAD

**Issue by dmarvp** [bespoken/virtual-device-sdk#115]
### Summary
Add a new class in the SDK called DeviceLocation, its constructor should receive two parameters Lat and Lng. These will correspond with the lat and lng parameters described here:

https://github.com/bespoken/virtual-device/issues/274

Use a decimal type for both parameters and add tests for it.

**Comment by ecruzado** [comment]
https://github.com/bespoken/virtual-device-sdk/pull/116

**Comment by MKen-li** [comment]
No QA needed
