### ISSUE TITLE
Add an optional "client" parameter to virtual device calls

### ISSUE THREAD

**Issue by dmarvp** [bespoken/virtual-device-sdk#121]
**Is your feature request related to a problem? Please describe.**
https://github.com/bespoken/virtual-device/issues/285

**Describe the solution you'd like**
Add an optional parameter when calling the virtual device endpoint for a client. The default value should be "sdk" but it should allow overwriting that value.

**Comment by ecruzado** [comment]
https://github.com/bespoken/virtual-device-sdk/pull/123

**Comment by ecruzado** [comment]
can be tested on virtual-device-sdk@1.5.15

**Comment by MKen-li** [comment]
No QA needed, closing ticket
