### ISSUE TITLE
Add an optional "screenMode" parameter 

### ISSUE THREAD

**Issue by dmarvp** [bespoken/virtual-device-sdk#122]
**Is your feature request related to a problem? **
https://github.com/bespoken/virtual-device/issues/287

**Description**
Add a "screenMode" property and tests for it that will set the "screenMode" parameter when calling the virtual device process or batch process endpoints.

**Comment by ecruzado** [comment]
https://github.com/bespoken/virtual-device-sdk/pull/123

**Comment by ecruzado** [comment]
can be tested on virtual-device-sdk@1.5.15

**Comment by MKen-li** [comment]
No QA needed
