### ISSUE TITLE
Treat homophones as lowercase

### ISSUE THREAD

**Issue by jkelvie** [bespoken/virtual-device-sdk#138]
Values specified in our homophone list should be matched case-insensitively.

For example, if someone defines a homophone like this:
```
{
  homophones: {
    "Kelvie": ["Kelly"]
  } 
}
```

We should replace either "kelly" or "Kelly" with Kelvie in the transcript from the virtual device. This is just a matter of setting the `i` flag on the regexp here:
https://github.com/bespoken/virtual-device-sdk/blob/master/src/VirtualDevice.ts#L398

**Comment by MKen-li** [comment]
Marked as verified
