### ISSUE TITLE
Lower case the expected value

### ISSUE THREAD

**Issue by dmarvp** [bespoken/virtual-device-sdk#54]
voice comparisons should be case insensitive, right now the skill responses are being changed to lower case but the expected values are not, which results in false cases of bad validation results.

**Comment by jkelvie** [comment]
We do the string comparisons in a case-sensitive way, as some of the fields, such as the card data, are case sensitive. I believe the comparisons should operate in a consistent way, though that does mean the user will need to make sure there expected values for transcripts are lowercase
