### ISSUE TITLE
Include the current sdk version in the bvd output.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/virtual-device-sdk#88]

**Comment by CoreyCole** [comment]
Something like this might get the job done, haven't tested it though... https://github.com/bespoken/virtual-device-sdk/pull/96

**Comment by jkelvie** [comment]
Hi @CoreyCole we recommend you use our latest version of bst with our new YAML syntax. Documentation is here:
https://read.bespoken.io/end-to-end/getting-started
