### ISSUE TITLE
Can't use virtual device SDK without https

### ISSUE THREAD

**Issue by dmarvp** [bespoken/virtual-device-sdk#97]
### Description:
The current implementation works only when virtual device is in an https environment. The port is hardcoded to 443:

https://github.com/bespoken/virtual-device-sdk/blob/7d720fc69fc9ef400189e564374f8ad22ace4f0d/src/VirtualDevice.ts#L117

We need to change it so that it also works with custom urls that don't use HTTPS.

### Steps To Reproduce
1. Have an instance of virtual device running at http://localhost:3000
2. set the env variable VIRTUAL_DEVICE_BASE_URL to that url 
2. do a request (from bst)

### Expected behavior
The response should be returned correctly.

### Actual behavior
We get an error response.

### Additional context
We need to remove the hardcoded 443 port on VirtualDevice.ts and probably change the library used from https to http.

Also update bst with a new version once this is done.

**Comment by ecruzado** [comment]
https://github.com/bespoken/virtual-device-sdk/pull/98

**Comment by MKen-li** [comment]
Marked as verified
Build bespoken-tools@2.1.1
